version: '3.7'

services:
  gcloud:
    image: google/cloud-sdk:338.0.0
    volumes:
      - gcp-creds:/creds
      - .:/bukmarkz
    working_dir: /bukmarkz
    environment:
      - CLOUDSDK_CONFIG=/creds

  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn bukmarkz.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  react:
    build:
      context: ./webapp
      dockerfile: Dockerfile.prod
    volumes:
      - react_build:/app/build
    depends_on:
      - web


  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
      - react_build:/app/build

    depends_on:
      - web
      - react

volumes:
  postgres_data:
  static_volume:
  media_volume:
  react_build:
  gcp-creds: