# Generated by Django 3.1.11 on 2021-12-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_discountable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionfeature',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
