# Generated by Django 3.1.11 on 2021-12-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20211209_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='currency',
            field=models.TextField(default='USD', editable=False, max_length=3),
        ),
    ]
