"""
Django settings for beepex_backend project.

Generated by 'django-admin startproject' using Django 3.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import logging
import os
from datetime import timedelta

from django.utils.translation import get_language_from_path
from django.utils.translation import ugettext_lazy as _
from rest_framework.settings import api_settings

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&@66g5tcpkf$#wyc6sb7r_690ls*oxf@dkxggpp&o8q@t1x8nc'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = os.environ.get("DEBUG", True)
# DEBUG_TOOLBAR = os.environ.get("DEBUG_TOOLBAR", False)
# PROD = not DEBUG

try:
    STAGING = os.environ.get('STAGING')
    # print('STAGING',STAGING)
    if STAGING == 'True':
        STAGING = True
    elif STAGING == 'False':
        STAGING = False
    elif STAGING == 'None':
        STAGING = None
except:
    STAGING =  None

if STAGING == False:
    DEBUG = False
    DEBUG_TOOLBAR = False
    PROD = False
else:
    DEBUG = True
    DEBUG_TOOLBAR = True
    PROD = False


ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    # "jet.dashboard",  # Admin Dashboard
    # "jet",  # New Admin panel
    'modeltranslation',
    'suit',
    'rosetta',  # for translation
    'ckeditor',
    'ckeditor_uploader',
    "widget_tweaks",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.sites",
    "django.contrib.sitemaps",
    'rest_framework',
    'rest_framework.authtoken',
    'rest_auth',
    'django_rest_passwordreset',
    'drf_yasg',
    "celery",  # Don't forget to add celery
    "django_celery_results",  # celery result
    "django_celery_beat",
    "rangefilter",
    "ajax_select",
    "mathfilters",


]
INSTALLED_APPS += [
    "core.apps.CoreConfig",
    "base_user.apps.BaseUserConfig",
    "flatpages.apps.FlatPagesConfig",
    "fcm.apps.FcmConfig",
    "ticket.apps.TicketConfig",
    "fulfillment.apps.FulfillmentConfig",
    "payment.apps.PaymentConfig",
    "custom_admin.apps.CustomAdminConfig",
]
if DEBUG_TOOLBAR:
    INSTALLED_APPS += [
        "debug_toolbar",
    ]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'beepex_backend.middleware.force_default_middleware.force_default_language_middleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'base_user.get_username.RequestMiddleware',

]

DJANGO_REST_PASSWORDRESET_NO_INFORMATION_LEAKAGE = True

if DEBUG_TOOLBAR:
    INTERNAL_IPS = ["127.0.0.1"]

    MIDDLEWARE = ["debug_toolbar.middleware.DebugToolbarMiddleware"] + MIDDLEWARE


logging.basicConfig(level=logging.INFO)


CKEDITOR_UPLOAD_PATH = "uploads/"


ROOT_URLCONF = 'beepex_backend.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'beepex_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": os.environ.get("POSTGRES_DB", "name_beepex_db"),
        "USER": os.environ.get("POSTGRES_USER", "user_bringly_db"),
        "PASSWORD": os.environ.get(
            "POSTGRES_PASSWORD", "6NwpPtvGyCsMLAKDZtazEP9WjANze25eP3e2UJdWrgrrKq"
        ),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_USER_MODEL = "base_user.MyUser"

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGES = (
    ('az', _('Azerbaijani')),
    ('ru', _('Russian')),
)

LANGUAGE_CODE = 'az'

TIME_ZONE = 'Asia/Baku'

USE_I18N = True

USE_L10N = True

USE_TZ = True


MODELTRANSLATION_DEFAULT_LANGUAGE = 'az'
MODELTRANSLATION_LANGUAGES = ('ru', 'az')

if not PROD:
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"


STATIC_URL = '/static/'

if PROD or STAGING:
    STATIC_ROOT = os.path.join(BASE_DIR, "static")
else:
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, "static")
    ]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)


SITE_ID=2

DEFAULT_RENDERER_CLASSES = ("rest_framework.renderers.JSONRenderer",)

if DEBUG:
    DEFAULT_RENDERER_CLASSES = DEFAULT_RENDERER_CLASSES + (
        "rest_framework.renderers.BrowsableAPIRenderer",
    )



REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_AUTHENTICATION_CLASSES": (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        # "knox.auth.TokenAuthentication",
    ),
    "DEFAULT_RENDERER_CLASSES": DEFAULT_RENDERER_CLASSES,
    "DATETIME_FORMAT": "%d.%m.%Y %H:%M",
    'EXCEPTION_HANDLER': 'api.utils.exception.custom_exception_handler'
}



#_________________________ Email notification configurations

DEFAULT_OFFICE_EMAIL = "Buyurun@bringly.az"

SENDGRID_API_KEY = "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"

EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'notify@bringly.az'
EMAIL_HOST_PASSWORD = 'mnbvcxz987'
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER 


# _________________________ SMS notification configurations

API_URL = "http://apps.lsim.az/quicksms/v1/send"
API_LOGIN = "bringlyaz"
API_SECRET = "yC35eH5L"
SENDER = "Bringly.az"

# _________________________ Special Grups

BEEPEX_GROUPS_COURIERS = "Courier"
BEEPEX_GROUPS_OPERATORS = "Operators"

# __________________________ Payment location

BIRKART_MERCHANT_KEY = "E1020027"
BIRKART_PAYMENT_HTTPS = "https://e-commerce.kapitalbank.az:5443/Exec"
BIRKART_SUCCESS_FORWARD_URL = "/payment/approve/"
BIRKART_DECLINE_FORWARD_URL = "/payment/decline/"

# __________________________ "IADEAL" (cashback service) API credentials

IADEAL_MERCHANTKEY = ""
IADEAL_TOKEN = ""
IADEAL_ENDPOINT = "https://api.iadeal.com/v1.0/deeplink/generate"


# __________________________ Authentication and authorization urls

LOGIN_URL = "account:login"
LOGIN_REDIRECT_URL = "core:dashboard-page"
LOGIN_ERROR_URL = "/"
LOGOUT_URL = "account:logout"


# __________________________ Default service tracking code prefixes

ORDER_TRACK_CODE = "OR85"
DECL_TRACK_CODE = "DE85"
COURIER_TRACK_CODE = "C85"

# __________________________ Paymes gateway credentials

PAYMES_API_SECRET_KEY = "ca85ebe96c85f4656bfa1a258ea06402"
PAYMES_API_URL_ROOT = "https://web.paym.es/gapi.php"

# __________________________ DGK configurations